# Generated by Django 3.2 on 2021-04-20 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreferences',
            name='age',
            field=models.CharField(default='no preference', max_length=13),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='gender',
            field=models.CharField(default='no preference', max_length=13),
        ),
    ]
