# Generated by Django 3.2 on 2021-04-21 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_api', '0002_auto_20210420_1451'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userpreferences',
            old_name='zip_code',
            new_name='location',
        ),
    ]
