# Generated by Django 3.2 on 2021-04-24 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_api', '0002_alter_usermatches_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermatches',
            name='photo',
            field=models.CharField(default='https://dl5zpyw5k3jeb.cloudfront.net/photos/pets/51279301/1/?bust=1619282109&width=300', max_length=1000),
            preserve_default=False,
        ),
    ]
