# Generated by Django 3.2 on 2021-04-24 16:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users_api', '0003_rename_zip_code_userpreferences_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMatches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.CharField(max_length=13)),
                ('gender', models.CharField(max_length=13)),
                ('size', models.CharField(max_length=7)),
                ('distance', models.CharField(max_length=7)),
                ('api_id', models.IntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
