# Generated by Django 3.2 on 2021-04-27 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_api', '0004_alter_usermatches_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermatches',
            name='age',
            field=models.CharField(default='Ageless', max_length=13),
        ),
        migrations.AlterField(
            model_name='usermatches',
            name='distance',
            field=models.CharField(default='0', max_length=7),
        ),
        migrations.AlterField(
            model_name='usermatches',
            name='gender',
            field=models.CharField(default='', max_length=13),
        ),
        migrations.AlterField(
            model_name='usermatches',
            name='name',
            field=models.CharField(default='Your 1st Match', max_length=50),
        ),
        migrations.AlterField(
            model_name='usermatches',
            name='photo',
            field=models.CharField(default='https://media.istockphoto.com/vectors/paw_print-vector-id931785704?k=6&m=931785704&s=612x612&w=0&h=nRInK4vazDBj-Jt8qJs2YJop_BKE0MjIcNAx2rRgwgI=', max_length=1000),
        ),
        migrations.AlterField(
            model_name='usermatches',
            name='size',
            field=models.CharField(default='', max_length=7),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='location',
            field=models.CharField(default='90210', max_length=5),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='type',
            field=models.CharField(default='Dog', max_length=7),
        ),
    ]
