# Generated by Django 3.2 on 2021-04-27 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_api', '0005_auto_20210427_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermatches',
            name='api_id',
            field=models.IntegerField(default=0),
        ),
    ]
